import os
import json
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from datetime import datetime

HISTORY_PATH = "data/history.json"
REPORTS_PATH = "static/reports"

def generate_pdf(user):
    """Generate a personalized daily report PDF."""
    os.makedirs(REPORTS_PATH, exist_ok=True)

    pdf_name = f"report_{user['name']}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    pdf_path = os.path.join(REPORTS_PATH, pdf_name)

    c = canvas.Canvas(pdf_path, pagesize=letter)
    width, height = letter

    # Header
    c.setFont("Helvetica-Bold", 20)
    c.drawString(50, height - 50, f"🍎 FoodAI 2.0 Daily Nutrition Report")

    c.setFont("Helvetica", 12)
    c.drawString(50, height - 90, f"Name: {user.get('name', '')}")
    c.drawString(50, height - 110, f"Age: {user.get('age', '')}")
    c.drawString(50, height - 130, f"Gender: {user.get('gender', '')}")
    c.drawString(50, height - 150, f"Date: {datetime.now().strftime('%d-%b-%Y %H:%M:%S')}")

    # Load history data
    if not os.path.exists(HISTORY_PATH):
        with open(HISTORY_PATH, "w") as f:
            json.dump([], f)
    try:
        with open(HISTORY_PATH, "r") as f:
            history = json.load(f)
    except json.JSONDecodeError:
        history = []

    today = datetime.now().date().isoformat()
    daily_foods = [item for item in history if item["date"] == today]

    # Draw Table
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 190, "Today's Meals:")
    y = height - 210
    c.setFont("Helvetica", 12)
    total_cal = 0

    if not daily_foods:
        c.drawString(70, y, "No entries for today.")
    else:
        for entry in daily_foods:
            text = f"- {entry['food']} : {entry['calories']} kcal at {entry['time']}"
            c.drawString(70, y, text)
            total_cal += float(entry["calories"])
            y -= 20

    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y - 20, f"Total Calories: {round(total_cal, 2)} kcal")

    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 50, "Generated by FoodAI 2.0 © 2025 | AI Nutrition Assistant")

    c.save()
    return pdf_path

